spring.datasource.url=jdbc:mysql://localhost:3306/reservation_system
spring.datasource.username=root
spring.datasource.password=root123
spring.jpa.hibernate.ddl-auto=update

# JWT Config
jwt.secret=mySuperSecretKey123456abcdefghij
jwt.expiration=3600000         